skip StackTraceElement in jdk17
sofastack/sofa-hessian pull request #79
Opened 2023-03-08 07:26 UTC by HzjNeverStop

2023-03-08 13:30 UTC, OrezzerO requested changes
Please explain why need this change. @HzjNeverStop

2023-03-08 13:30 UTC, OrezzerO commented on src/main/java/com/caucho/hessian/io/SerializerFactory.java
> +    private static boolean isJava17() {
Method name may be `isEauqlOrHigher17`

2023-03-20 06:25 UTC, HzjNeverStop commented on src/main/java/com/caucho/hessian/io/SerializerFactory.java
> +    private static boolean isJava17() {
和已有的 isJava8() 方法保持一致的命名风格

2023-03-20 11:06 UTC, OrezzerO commented on src/main/java/com/caucho/hessian/io/SerializerFactory.java
> +    private static boolean isJava17() {
向来如此便对吗[狗头] 要不两个都改了吧

2023-03-20 11:17 UTC, HzjNeverStop commented on src/main/java/com/caucho/hessian/io/SerializerFactory.java
> +    private static boolean isJava17() {
> 向来如此便对吗[狗头] 要不两个都改了吧

已修改。

2023-04-14 02:33 UTC, OrezzerO approved these changes
LGTM

2023-05-10 09:45 UTC, closed without merging